anthropic_version: bedrock-2023-05-31
max_tokens: 1000
temperature: 0
system: Respond valid json format.
# https://docs.anthropic.com/claude/docs/control-output-format#prefilling-claudes-response
messages:
    [{ "role": "user", "content": [{ "type": "text", "text": "{prompt}" }] },
    {"role": "assistant", "content": [{ "type": "text", "text": "{" }]}]
stop_sequences: ["</output>"]

stream: false
model_id: anthropic.claude-3-haiku-20240307-v1:0
