anthropic_version: bedrock-2023-05-31
max_tokens: 1000
temperature: 0
system: Respond only the answer in Japanese.
messages:
    [{ "role": "user", "content": [{ "type": "text", "text": "{prompt}" }] }]
stop_sequences: ["</output>"]

stream: false
model_id: anthropic.claude-3-haiku-20240307-v1:0
# model_id: anthropic.claude-3-sonnet-20240229-v1:0
# model_id: anthropic.claude-3-opus-20240229-v1:0
