max_tokens: 1000
temperature: 0
message: "{prompt}"
chat_history:
        [{ "role": "USER", "message": "Respond only in Japanese" },
        { "role": "CHATBOT", "message": "承知しました。何について話しましょうか？"}]
stop_sequences: ["</output>"]

stream: false
model_id: cohere.command-r-plus-v1:0
